SET NAMES 'UTF8MB4';
DROP DATABASE IF EXISTS hoteles;
CREATE DATABASE IF NOT EXISTS hoteles DEFAULT CHARACTER SET UTF8MB4;
USE hoteles;

CREATE TABLE gerentes (
id_gerente			INTEGER NOT NULL AUTO_INCREMENT,
nombre			VARCHAR(40) NOT NULL,
ap_paterno		VARCHAR(15) NOT NULL,
ap_materno		VARCHAR(15) NOT NULL,
telefono		VARCHAR(10) NOT NULL,
PRIMARY KEY(id_gerente)
) DEFAULT CHARACTER SET UTF8MB4;

CREATE TABLE hoteles (
id_hotel			INTEGER NOT NULL AUTO_INCREMENT,
nombre			VARCHAR(40) NOT NULL,
direccion		VARCHAR(100) NOT NULL,
telefono		VARCHAR(10) NOT NULL,
correo			VARCHAR(30) NOT NULL,
id_gerentre		INTEGER,
PRIMARY KEY(id_hotel)
FOREIGN KEY(id_gerente) REFERENCES gerentes(id_gerente)
) DEFAULT CHARACTER SET UTF8MB4;

CREATE TABLE habitaciones (
id_habitacion		INTEGER NOT NULL AUTO_INCREMENT,
nombre			VARCHAR(40) NOT NULL,
piso			VARCHAR(10) NOT NULL,
refrigerador		BOOLEAN	    NOT NULL,
id_hotel		INTEGER,
PRIMARY KEY(id_hotel)
FOREIGN KEY(id_habitacion) REFERENCES habitacioness(id_hotel)
) DEFAULT CHARACTER SET UTF8MB4;

